apiVersion: v2
appVersion: 2.9.2
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 12.2.3
- condition: solr.enabled
  name: solr
  repository: https://charts.helm.sh/incubator
  version: 1.4.0
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.2.0
- condition: datapusher.enabled
  name: datapusher
  repository: https://keitaro-charts.storage.googleapis.com
  version: 1.0.0
description: CKAN Helm chart
name: ckan
type: application
version: 1.0.2
